#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
# shellcheck disable=SC2207
set -CeEuo pipefail
IFS=$'\n\t'
trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
cd -- "$(dirname -- "$0")"/..

# Generates code based on target-spec.
#
# USAGE:
#    ./tools/target_spec.sh
#
# This script is intended to be called by gen.sh, but can be called separately.

bail() {
  printf >&2 'error: %s\n' "$*"
  exit 1
}

utils_file=src/gen/utils.rs
build_file=src/gen/build.rs
mkdir -p -- "$(dirname -- "${utils_file}")"
mkdir -p -- "$(dirname -- "${build_file}")"

known_64_bit_arch=($(rustc -Z unstable-options --print all-target-specs-json | jq -r '. | to_entries[].value | if ."target-pointer-width" == 64 then .arch else empty end' | LC_ALL=C sort -u))

cat >|"${utils_file}" <<EOF
// SPDX-License-Identifier: Apache-2.0 OR MIT
// This file is @generated by ${0##*/}.
// It is not intended for manual editing.

#![allow(dead_code, unused_macros)]

// On AArch64, the base register of memory-related instructions must be 64-bit.
// Passing a 32-bit value to \`in(reg)\` on AArch64 results in the upper bits
// having an undefined value, but to work correctly with ILP32 ABI, the upper
// bits must be zero, which is handled here by casting to u64. Another way to
// handle this is to pass it as a pointer and clear the upper bits inside asm,
// but it is easier to overlook than cast, which can catch overlooks by
// asm_sub_register lint.
// See also https://github.com/ARM-software/abi-aa/blob/2025Q4/aapcs64/aapcs64.rst#pointers
//
// Except for x86_64, which can use 32-bit registers in the destination operand
// (on x86_64, we use the ptr_modifier macro to handle this), we need to do the
// same for ILP32 ABI on other 64-bit architectures. (At least, as far as I can
// see from the assembly generated by LLVM, this is also required for MIPS64 N32
// ABI. I don't know about other similar ABIs, but in any case, this should be
// a safe default for such ABIs).
//
// Known architectures that have such ABI are x86_64 (X32), AArch64 (ILP32),
// mips64/mips64r6 (N32), riscv64 (RV64ILP32*), PowerPC64 (Lv2). (As of
// 2026-03-22, only the former two are supported by rustc.) However, we list
// all known 64-bit architectures because similar ABIs may exist or future added
// for other architectures.
#[cfg(all(
    target_pointer_width = "32",
    any(
$(sed -E 's/^/        target_arch = "/g; s/$/",/g' <<<"${known_64_bit_arch[*]}")
    ),
))]
#[macro_use]
mod imp {
    #[cfg(not(any(target_arch = "x86", target_arch = "x86_64")))]
    macro_rules! ptr_reg {
        (\$ptr:ident) => {{
            let _: *const _ = \$ptr; // ensure \$ptr is a pointer (*mut _ or *const _)
            #[allow(clippy::ptr_as_ptr)]
            {
                // If we cast to u64 here, the provenance will be lost,
                // so we convert to MaybeUninit<u64> via zero extend helper.
                crate::utils::zero_extend64::ptr(\$ptr as *mut ())
            }
        }};
    }
    pub(crate) type RegSize = u64;
}
#[cfg(not(all(
    target_pointer_width = "32",
    any(
$(sed -E 's/^/        target_arch = "/g; s/$/",/g' <<<"${known_64_bit_arch[*]}")
    ),
)))]
#[macro_use]
mod imp {
    #[cfg(not(any(target_arch = "x86", target_arch = "x86_64")))]
    macro_rules! ptr_reg {
        (\$ptr:ident) => {{
            let _: *const _ = \$ptr; // ensure \$ptr is a pointer (*mut _ or *const _)
            \$ptr // cast is unnecessary here.
        }};
    }
EOF
for size in '16' '32' '64' '128'; do
  cat >>"${utils_file}" <<EOF
    #[cfg(target_pointer_width = "${size}")]
    pub(crate) type RegSize = u${size};
EOF
done
cat >>"${utils_file}" <<EOF
}
pub(crate) use self::imp::RegSize;
EOF

# TODO: https://github.com/llvm/llvm-project/blob/llvmorg-23.1.0-rc3/llvm/lib/Target/AArch64/AArch64Processors.td
#       uses a lot of ProcessorAlias...
# target=aarch64-unknown-none-softfloat
# aarch64_lse2=()
# aarch64_lse128=()
# aarch64_rcpc3=()
# cpus=$(rustc --print target-cpus --target "${target}")
# while IFS= read -r cpu; do
#   cfgs=$(rustc --print cfg --target "${target}" -C target-cpu="${cpu}")
#   target_features=$(grep -E '^target_feature=' <<<"${cfgs}" || true)
#   if [[ "${target_features}" == *"\"lse2\""* ]]; then
#     aarch64_lse2+=("${cpu}")
#   fi
#   if [[ "${target_features}" == *"\"lse128\""* ]]; then
#     aarch64_lse128+=("${cpu}")
#   fi
#   if [[ "${target_features}" == *"\"rcpc3\""* ]]; then
#     aarch64_rcpc3+=("${cpu}")
#   fi
# done < <(grep -E '^    ' <<<"${cpus}" | sed -E 's/^    //g; s/ .*//g; /^native$/d')

target=powerpc-unknown-linux-gnu
powerpc_msync=()
powerpc_partword_quadword_atomics=()
cpus=$(rustc --print target-cpus --target "${target}")
while IFS= read -r cpu; do
  if [[ "${cpu}" == 'future' ]]; then
    # In the recent LLVM, "future" is based on pwr11 features,
    # https://github.com/llvm/llvm-project/blob/llvmorg-23.1.0-rc1/llvm/lib/Target/PowerPC/PPC.td#L571
    # but on the minimum external LLVM version of the oldest rustc version which we can use asm_experimental_arch
    # on this target (see matrix.sh), "future" is based on pwr10 features.
    # https://github.com/llvm/llvm-project/blob/llvmorg-12.0.0/llvm/lib/Target/PowerPC/PPC.td#L370
    cfgs=$(rustc --print cfg --target "${target}" -C target-cpu=pwr10)
  else
    cfgs=$(rustc --print cfg --target "${target}" -C target-cpu="${cpu}")
  fi
  target_features=$(grep -E '^target_feature=' <<<"${cfgs}" || true)
  if [[ "${target_features}" == *"\"msync\""* ]]; then
    powerpc_msync+=("${cpu}")
  fi
  if [[ "${target_features}" == *"\"partword-atomics\""* ]] && [[ "${target_features}" == *"\"quadword-atomics\""* ]]; then
    powerpc_partword_quadword_atomics+=("${cpu}")
  fi
done < <(grep -E '^    ' <<<"${cpus}" | sed -E 's/^    //g; s/ .*//g; /^native$/d')

target=sparc-unknown-none-elf
sparc_leoncasa=()
sparc_v9=()
cpus=$(rustc --print target-cpus --target "${target}")
while IFS= read -r cpu; do
  cfgs=$(rustc --print cfg --target "${target}" -C target-cpu="${cpu}")
  target_features=$(grep -E '^target_feature=' <<<"${cfgs}" || true)
  if [[ "${target_features}" == *"\"leoncasa\""* ]]; then
    sparc_leoncasa+=("${cpu}")
  fi
  if [[ "${target_features}" == *"\"v9\""* ]]; then
    sparc_v9+=("${cpu}")
  fi
done < <(grep -E '^    ' <<<"${cpus}" | sed -E 's/^    //g; s/ .*//g; /^native$/d')

target=m68k-unknown-none-elf
m68k_isa_68020=()
m68k_isa_68060=()
cpus=$(rustc --print target-cpus --target "${target}")
while IFS= read -r cpu; do
  cfgs=$(rustc --print cfg --target "${target}" -C target-cpu="${cpu}")
  target_features=$(grep -E '^target_feature=' <<<"${cfgs}" || true)
  if [[ "${target_features}" == *"\"isa-68020\""* ]]; then
    m68k_isa_68020+=("${cpu}")
  fi
  if [[ "${target_features}" == *"\"isa-68060\""* ]]; then
    m68k_isa_68060+=("${cpu}")
  fi
done < <(grep -E '^    ' <<<"${cpus}" | sed -E 's/^    //g; s/ .*//g; /^native$/d')

target=avr-none
avr_tinyencoding=()
avr_rmw=()
avr_lowbytefirst=()
cpus=$(rustc --print target-cpus --target "${target}")
while IFS= read -r cpu; do
  cfgs=$(rustc --print cfg --target "${target}" -C target-cpu="${cpu}")
  target_features=$(grep -E '^target_feature=' <<<"${cfgs}" || true)
  if [[ "${target_features}" == *"\"tinyencoding\""* ]]; then
    avr_tinyencoding+=("${cpu}")
  fi
  if [[ "${target_features}" == *"\"rmw\""* ]]; then
    avr_rmw+=("${cpu}")
  fi
  if [[ "${target_features}" == *"\"lowbytefirst\""* ]]; then
    avr_lowbytefirst+=("${cpu}")
  fi
done < <(grep -E '^    ' <<<"${cpus}" | sed -E 's/^    //g; s/ .*//g; /^native$/d')

arm_but_thumb_mode=()
thumb_but_arm_mode=()
specs=$(rustc -Z unstable-options --print all-target-specs-json)
while IFS= read -r target; do
  cfgs=$(rustc --print cfg --target "${target}")
  target_features=$(grep -E '^target_feature=' <<<"${cfgs}" || true)
  case "${target}" in
    thumb*)
      if [[ "${target_features}" != *"\"thumb-mode\""* ]]; then
        thumb_but_arm_mode+=("${target}")
      fi
      ;;
    *)
      if [[ "${target_features}" == *"\"thumb-mode\""* ]]; then
        arm_but_thumb_mode+=("${target}")
      fi
      ;;
  esac
done < <(jq -r '. | to_entries[] | if .value.arch == "arm" then .key else empty end' <<<"${specs}")
if [[ ${#thumb_but_arm_mode[@]} -ne 0 ]]; then
  IFS=' '
  bail "thumb* but in arm mode...: ${thumb_but_arm_mode[*]}"
fi

# sort and dedup
IFS=$'\n'
# aarch64_lse2=($(LC_ALL=C sort -u <<<"${aarch64_lse2[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
# aarch64_lse128=($(LC_ALL=C sort -u <<<"${aarch64_lse128[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
# aarch64_rcpc3=($(LC_ALL=C sort -u <<<"${aarch64_rcpc3[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
powerpc_msync=($(LC_ALL=C sort -u <<<"${powerpc_msync[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
powerpc_partword_quadword_atomics=($(LC_ALL=C sort -u <<<"${powerpc_partword_quadword_atomics[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
sparc_leoncasa=($(LC_ALL=C sort -u <<<"${sparc_leoncasa[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
sparc_v9=($(LC_ALL=C sort -u <<<"${sparc_v9[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
m68k_isa_68020=($(LC_ALL=C sort -u <<<"${m68k_isa_68020[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
m68k_isa_68060=($(LC_ALL=C sort -u <<<"${m68k_isa_68060[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
avr_tinyencoding=($(LC_ALL=C sort -u <<<"${avr_tinyencoding[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
avr_rmw=($(LC_ALL=C sort -u <<<"${avr_rmw[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
avr_lowbytefirst=($(LC_ALL=C sort -u <<<"${avr_lowbytefirst[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
arm_but_thumb_mode=($(LC_ALL=C sort -u <<<"${arm_but_thumb_mode[*]}" | sed -E 's/^/    "/g; s/$/",/g; /^ *"",/d'))
IFS=$'\n\t'

cat >|"${build_file}" <<EOF
// SPDX-License-Identifier: Apache-2.0 OR MIT
// This file is @generated by ${0##*/}.
// It is not intended for manual editing.

#![cfg_attr(rustfmt, rustfmt::skip)]

EOF

print_list() {
  local name="$1"
  shift
  local list=${*+"$*"$'\n'}
  cat >>"${build_file}" <<EOF
pub(crate) static ${name}: &[&str] = &[
${list}];
EOF
}
# print_list AARCH64_LSE2_CPU "${aarch64_lse2[@]}"
# print_list AARCH64_LSE128_CPU "${aarch64_lse128[@]}"
# print_list AARCH64_RCPC3_CPU "${aarch64_rcpc3[@]}"
print_list POWERPC_MSYNC_CPU "${powerpc_msync[@]}"
print_list POWERPC_PARTWORD_QUADWORD_ATOMICS_CPU "${powerpc_partword_quadword_atomics[@]}"
print_list SPARC_LEONCASA_CPU "${sparc_leoncasa[@]}"
print_list SPARC_V9_CPU "${sparc_v9[@]}"
print_list M68K_ISA_68020_CPU "${m68k_isa_68020[@]}"
print_list M68K_ISA_68060_CPU "${m68k_isa_68060[@]}"
print_list AVR_TINYENCODING_CPU "${avr_tinyencoding[@]}"
print_list AVR_RMW_CPU "${avr_rmw[@]}"
print_list AVR_LOWBYTEFIRST_CPU "${avr_lowbytefirst[@]}"
print_list ARM_BUT_THUMB_MODE "${arm_but_thumb_mode[@]}"
